import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";

// Utility to convert Base64 VAPID to Uint8Array required by pushManager
function urlBase64ToUint8Array(base64String: string) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/\-/g, "+").replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export function useWebPush() {
  const [isSubscribed, setIsSubscribed] = useState(false);
  const [isSupported, setIsSupported] = useState(false);
  const [permission, setPermission] = useState<NotificationPermission>("default");

  useEffect(() => {
    if ("serviceWorker" in navigator && "PushManager" in window) {
      setIsSupported(true);
      setPermission(Notification.permission);
      
      navigator.serviceWorker.register("/sw.js").then((registration) => {
        registration.pushManager.getSubscription().then((sub) => {
          setIsSubscribed(sub !== null);
        });
      });
    }
  }, []);

  const subscribe = async (userId: string) => {
    if (!isSupported) {
      console.warn("Push notifications are not supported in this browser");
      return false;
    }

    try {
      const permissionResult = await Notification.requestPermission();
      setPermission(permissionResult);
      if (permissionResult !== "granted") {
        throw new Error("Permission not granted for Notification");
      }

      const registration = await navigator.serviceWorker.ready;
      
      const vapidPublicKey = import.meta.env.VITE_VAPID_PUBLIC_KEY;
      if (!vapidPublicKey) {
         console.warn("VITE_VAPID_PUBLIC_KEY not configured in .env");
         return false;
      }

      const convertedVapidKey = urlBase64ToUint8Array(vapidPublicKey);

      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedVapidKey,
      });

      const subJSON = subscription.toJSON();
      if (!subJSON.endpoint || !subJSON.keys?.p256dh || !subJSON.keys?.auth) {
         throw new Error("Invalid subscription data generated by browser");
      }

      // Save to Supabase (using direct upsert if composite key isn't working, but relying on trigger or distinct queries later)
      // Since we defined UNIQUE(user_id, endpoint), we can rely on ignoring duplicates or updating them.
      const { error } = await supabase.from("push_subscriptions" as any).upsert({
        user_id: userId,
        endpoint: subJSON.endpoint,
        p256dh: subJSON.keys.p256dh,
        auth: subJSON.keys.auth
      }, { onConflict: "user_id, endpoint" });

      if (error) {
        console.error("Supabase upsert push_subscriptions error:", error);
        throw error;
      }

      setIsSubscribed(true);
      return true;
    } catch (err) {
      console.error("Failed to subscribe user to push notifications: ", err);
      return false;
    }
  };

  return {
    isSupported,
    isSubscribed,
    permission,
    subscribe
  };
}
